import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gold text-crimson`}
      >
        <nav className="w-full flex justify-center gap-8 p-4 text-base font-medium text-crimson bg-gold/90 shadow-sm sticky top-0 z-50">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/pay">Post Rishta</Link>
          <Link href="/portfolio">Portfolio</Link>
          <Link href="/terms">Terms</Link>
          <Link href="/contact">Contact</Link>
          <Link href="/admin">Admin</Link>
        </nav>
        {children}
        <footer className="w-full mt-16 py-6 bg-crimson text-gold border-t border-gold/30 text-center text-sm">
          <div className="mb-2">
            <Link href="/" className="font-semibold text-gold hover:underline">Hijab Marriage Bureau</Link> &mdash; Dignified, Shariah-compliant matchmaking for Muslims
          </div>
          <div>&copy; {new Date().getFullYear()} Hijab Marriage Bureau. All rights reserved.</div>
        </footer>
      </body>
    </html>
  );
}
