import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { authOptions } from "@/lib/authOptions";
import "./globals.css";
import { LogoutButton } from "@/components/logoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gold text-crimson`}
      >
        <nav className="w-full flex items-center justify-between p-4 text-base font-medium text-white bg-black/90 shadow-sm sticky top-0 z-50">
          <div className="flex justify-center gap-8 ml-25">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/pay">Post Rishta</Link>
            <Link href="/portfolio">Portfolio</Link>
            <Link href="/terms">Terms</Link>
            <Link href="/contact">Contact</Link>
          </div>
          {(session ? <LogoutButton/> :(
            <Link
              className="bg-amber-500 text-sm p-1.5 mx-3 rounded-xl hover:underline"
              href="/login"
            >
              SignIn
            </Link>))
          }
          
        </nav>
        {children}
        <footer className="w-full mt-16 py-6 bg-crimson text-gold border-t border-gold/30 text-center text-sm">
          <div className="mb-2">
            <Link href="/" className="font-semibold text-gold hover:underline">
              Hijab Marriage Bureau
            </Link>{" "}
            &mdash; Dignified, Shariah-compliant matchmaking for Muslims
          </div>
          <div>
            &copy; {new Date().getFullYear()} Hijab Marriage Bureau. All rights
            reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
